[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
(
  /(
      \.*.pyc
    | __pycache__
    | node_modules
  )/
)
'''

[tool.mypy]
python_version = 3.11
ignore_missing_imports = "True"
follow_imports_for_stubs = "True"
show_column_numbers = "True"
scripts_are_modules = "True"
no_implicit_optional = "False"
strict_optional = "False"
warn_unreachable = "True"
warn_unused_configs = "True"
warn_unused_ignores = "True"